package gui;

import java.awt.BorderLayout;
import java.awt.Dimension;

import javax.swing.JFrame;
import javax.swing.SwingUtilities;
import entitiesAndControl.GameField;
import main.SharedVariables;

/**
 * 
 * The main frame of the game
 * 
 * @author joanna czernicka
 *
 */
public class GameFrame extends JFrame {

	// Variables declarations
	private static final long serialVersionUID = 1L; // Autogenerated
	private int gameHeight;
	private int gameWidth;

	// ----------------------------------------------------------------------
	/**
	 * Class constructor
	 */
	public GameFrame() {

		gameHeight = SharedVariables.GAME_HEIGHT;
		gameWidth = SharedVariables.GAME_WIDTH;

		SwingUtilities.invokeLater(new Runnable() {
			public void run() {
				create();
			}
		});
	}

	// --------------METHODS--------------------------------------------------------

	/**
	 * creation of the JFrame and inserting mainJPanel inside it
	 */
	public void create() {
		JFrame frame = new JFrame("Snake");

		Dialog dialog = new Dialog();
		dialog.chooseLevel();
		if ((GameField.getSpeed() <= SharedVariables.LEVEL_EASY
				&& GameField.getSpeed() >= SharedVariables.LEVEL_HARD)) {
			MainJPanel mainJPanel = new MainJPanel();
			frame.getContentPane().add(mainJPanel, BorderLayout.CENTER);
		} else {
			System.exit(0);
		}

		frame.setResizable(false);
		frame.setPreferredSize(new Dimension(gameWidth, gameHeight));
		frame.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
		frame.setVisible(true);
		frame.pack();
		frame.setLocationRelativeTo(null);
	}

}
